service:
  name: linkbit-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2

functions:
  getAddress:
    handler: handlers.getLinkAddress
    events:
      - http:
          method: get
          path: address
          cors: true
  createAddress:
    handler: handlers.createAddress
    events:
      - http:
          method: post
          path: address
          cors: true
  linkAddress:
    handler: handlers.linkAddress
    events:
      - http:
          method: put
          path: address/link
          cors: true
  unlinkAddress:
    handler: handlers.unlinkAddress
    events:
      - http:
          method: delete
          path: address/link
          cors: true
  getCertText:
    handler: handlers.getCertText
    events:
      - http:
          method: get
          path: cert
          cors: true
 
