service:
  name: beer-shop-backend

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs10.x
  region: ap-northeast-2

functions:
  getItems:
    handler: handlers.getItems
    events:
      - http:
          method: get
          path: api/beers
          cors: true
  getItemsCors:
    handler: handlers.corsHandler
    events:
      - http:
          method: options
          path: api/beers
          cors: true
  getTags:
    handler: handlers.getTags
    events:
      - http:
          method: get
          path: api/tags
          cors: true
  getTagsCors:
    handler: handlers.corsHandler
    events:
      - http:
          method: options
          path: api/tags
          cors: true
  purchase:
    handler: handlers.purchase
    events:
      - http:
          method: post
          path: api/purchase
          cors: true
  purchaseCors:
    handler: handlers.corsHandler
    events:
      - http:
          method: options
          path: api/purchase
          cors: true
